# Generated by Django 6.0.3 on 2026-03-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='object_id',
            field=models.CharField(max_length=50),
        ),
    ]
